name: physiolink_frontend
description: A new Flutter project for Physiolink.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.0.3
  riverpod_annotation: ^3.0.3
  dio: ^5.9.0
  go_router: ^17.0.0
  flutter_secure_storage: ^9.2.4
  google_fonts: ^6.3.3
  json_annotation: ^4.9.0
  freezed_annotation: ^3.1.0
  intl: ^0.20.2
  jwt_decoder: ^2.0.1
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.10.4
  riverpod_generator: ^3.0.3
  freezed: ^3.2.3
  json_serializable: ^6.11.2

flutter:
  uses-material-design: true
